// Compiled SQL queries from dbt models
// These match the logic in dbt/models/marts/core/
// In a full deployment, these would be auto-generated by dbt compile

export const DIM_EXERCISE_SQL = `
WITH all_exercise_events AS (
    SELECT
        _event_id,
        _created_at,
        event_type,
        payload->>'exercise_id' AS exercise_id,
        payload->>'name' AS name,
        payload->>'muscle_group' AS muscle_group,
        CAST(payload->>'is_global' AS BOOLEAN) AS is_global,
        NULLIF(payload->>'gym_id', 'null') AS gym_id
    FROM events
    WHERE event_type IN ('exercise_created', 'exercise_updated', 'exercise_deleted')
),

deduplicated AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY exercise_id
            ORDER BY _created_at DESC
        ) AS _rn
    FROM all_exercise_events
),

active_exercises AS (
    SELECT
        exercise_id,
        name,
        muscle_group,
        is_global,
        gym_id,
        _created_at AS first_created_at,
        _created_at AS last_updated_at
    FROM deduplicated
    WHERE _rn = 1 AND event_type != 'exercise_deleted'
)

SELECT * FROM active_exercises
ORDER BY name
`;

export const DIM_GYM_SQL = `
WITH all_gym_events AS (
    SELECT
        _event_id,
        _created_at,
        event_type,
        payload->>'gym_id' AS gym_id,
        payload->>'name' AS name,
        NULLIF(payload->>'location', 'null') AS location
    FROM events
    WHERE event_type IN ('gym_created', 'gym_updated', 'gym_deleted')
),

deduplicated AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY gym_id
            ORDER BY _created_at DESC
        ) AS _rn
    FROM all_gym_events
),

active_gyms AS (
    SELECT
        gym_id,
        name,
        location,
        _created_at AS first_created_at,
        _created_at AS last_updated_at
    FROM deduplicated
    WHERE _rn = 1 AND event_type != 'gym_deleted'
)

SELECT * FROM active_gyms
ORDER BY name
`;
